# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ZU4ZU9-ZIDYrWqrvrkG8tJIxzcU-j_Y
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# ==========================
# Page Configuration
# ==========================
st.set_page_config(
    page_title="Telco Customer Churn Prediction",
    page_icon="📊",
    layout="wide"
)

# ==========================
# Load Files
# ==========================
model = joblib.load("churn_model.pkl")
scaler = joblib.load("scaler.pkl")
feature_names = joblib.load("feature_names.pkl")
metadata = joblib.load("metadata.pkl")

# ==========================
# Header
# ==========================
st.title("📊 Telco Customer Churn Prediction App")

st.write(
    """
Predict whether a telecom customer is likely to churn
using Machine Learning (Gaussian Naive Bayes Model).
"""
)

st.sidebar.header("Customer Information")

# ==========================
# Helper Function
# ==========================

def encode_binary(value):

    mapping = {
        "No":0,
        "Yes":1,
        "Female":0,
        "Male":1
    }

    return mapping.get(value,0)

# ==========================
# Inputs
# ==========================

gender = st.sidebar.selectbox(
    "Gender",
    ["Female","Male"]
)

senior = st.sidebar.selectbox(
    "Senior Citizen",
    ["No","Yes"]
)

partner = st.sidebar.selectbox(
    "Partner",
    ["No","Yes"]
)

dependents = st.sidebar.selectbox(
    "Dependents",
    ["No","Yes"]
)

tenure = st.sidebar.slider(
    "Tenure (Months)",
    0,
    72,
    12
)

phone = st.sidebar.selectbox(
    "Phone Service",
    ["No","Yes"]
)

multiple = st.sidebar.selectbox(
    "Multiple Lines",
    ["No","Yes"]
)

internet = st.sidebar.selectbox(
    "Internet Service",
    ["DSL","Fiber optic","No"]
)

security = st.sidebar.selectbox(
    "Online Security",
    ["No","Yes"]
)

backup = st.sidebar.selectbox(
    "Online Backup",
    ["No","Yes"]
)

device = st.sidebar.selectbox(
    "Device Protection",
    ["No","Yes"]
)

support = st.sidebar.selectbox(
    "Tech Support",
    ["No","Yes"]
)

tv = st.sidebar.selectbox(
    "Streaming TV",
    ["No","Yes"]
)

movies = st.sidebar.selectbox(
    "Streaming Movies",
    ["No","Yes"]
)

contract = st.sidebar.selectbox(
    "Contract",
    ["Month-to-month","One year","Two year"]
)

paperless = st.sidebar.selectbox(
    "Paperless Billing",
    ["No","Yes"]
)

payment = st.sidebar.selectbox(
    "Payment Method",
    [
        "Electronic check",
        "Mailed check",
        "Bank transfer",
        "Credit card"
    ]
)

monthly = st.sidebar.slider(
    "Monthly Charges",
    0.0,
    150.0,
    70.0
)

total = st.sidebar.number_input(
    "Total Charges",
    0.0,
    10000.0,
    1000.0
)

# ==========================
# Feature Engineering
# ==========================

avg_spend = total/(tenure+1)

service_count = sum([
    phone=="Yes",
    security=="Yes",
    backup=="Yes",
    device=="Yes",
    support=="Yes",
    tv=="Yes",
    movies=="Yes"
])

engagement = (
    tenure*0.4 +
    service_count*5
)

long_term = 1 if tenure>=24 else 0

high_monthly = 1 if monthly>=80 else 0

paper_flag = encode_binary(paperless)

tenure_group = 0

if tenure<12:
    tenure_group=0
elif tenure<24:
    tenure_group=1
elif tenure<48:
    tenure_group=2
else:
    tenure_group=3

monthly_cat = 0

if monthly<35:
    monthly_cat=0
elif monthly<70:
    monthly_cat=1
else:
    monthly_cat=2

total_cat=0

if total<1000:
    total_cat=0
elif total<3000:
    total_cat=1
else:
    total_cat=2

senior_cat = encode_binary(senior)

# ==========================
# Label Encoding
# ==========================

internet_map = {
    "DSL":0,
    "Fiber optic":1,
    "No":2
}

contract_map = {
    "Month-to-month":0,
    "One year":1,
    "Two year":2
}

payment_map = {
    "Electronic check":0,
    "Mailed check":1,
    "Bank transfer":2,
    "Credit card":3
}

# ==========================
# Create Data
# ==========================

input_data = pd.DataFrame([{

'gender':encode_binary(gender),
'SeniorCitizen':encode_binary(senior),
'Partner':encode_binary(partner),
'Dependents':encode_binary(dependents),
'tenure':tenure,
'PhoneService':encode_binary(phone),
'MultipleLines':encode_binary(multiple),
'InternetService':internet_map[internet],
'OnlineSecurity':encode_binary(security),
'OnlineBackup':encode_binary(backup),
'DeviceProtection':encode_binary(device),
'TechSupport':encode_binary(support),
'StreamingTV':encode_binary(tv),
'StreamingMovies':encode_binary(movies),
'Contract':contract_map[contract],
'PaperlessBilling':encode_binary(paperless),
'PaymentMethod':payment_map[payment],
'MonthlyCharges':monthly,
'TotalCharges':total,
'TenureGroup':tenure_group,
'MonthlyChargesCategory':monthly_cat,
'TotalChargesCategory':total_cat,
'AverageMonthlySpend':avg_spend,
'EngagementScore':engagement,
'ServiceCount':service_count,
'LongTermCustomer':long_term,
'HighMonthlyCharges':high_monthly,
'PaperlessBillingFlag':paper_flag,
'SeniorCitizenCategory':senior_cat

}])

input_data=input_data[feature_names]

scaled=scaler.transform(input_data)

# ==========================
# Prediction
# ==========================

if st.button("Predict Churn"):

    prediction=model.predict(scaled)[0]

    probability=model.predict_proba(
        scaled
    )[0][1]

    st.subheader("Prediction Result")

    if prediction==1:

        st.error(
            f"Customer likely to CHURN\n\nRisk Probability: {probability:.2%}"
        )

    else:

        st.success(
            f"Customer likely to STAY\n\nConfidence: {(1-probability):.2%}"
        )

    st.progress(float(probability))

# ==========================
# Footer
# ==========================

st.markdown("---")

st.caption(
f"""
Model: {metadata['Model']}

Target: {metadata['Target']}

Version: {metadata['Version']}
"""
)